version: '3.8'
services:
  order-service:
      build:
        context: ./../order-service
        dockerfile: Dockerfile
      environment:
          KAFKA_BROKERS: ${DOCKER_HOST_IP}:9092;${DOCKER_HOST_IP}:9093;${DOCKER_HOST_IP}:9094
          #SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/order-db?useUnicode=true&characterEncoding=utf8&useSSL=false
      ports:
          - 9192:9192
  credit-service:
      build:
        context: ./../credit-service
        dockerfile: Dockerfile
      environment:
          KAFKA_BROKERS: ${DOCKER_HOST_IP}:9092;${DOCKER_HOST_IP}:9093;${DOCKER_HOST_IP}:9094
          #SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/order-db?useUnicode=true&characterEncoding=utf8&useSSL=false
      ports:
          - 9191:9191