server:
  port: 9191

spring:
  cloud:
    stream:
      kafka:
          binder:
            brokers: ${KAFKA_BROKERS:localhost}
      function:
        definition: creditOrderEventProcessor
      bindings:
        creditOrderEventProcessor-in-0:
          destination: order-credit
        creditOrderEventProcessor-out-0:
          destination: credit-order
  datasource:
    url: jdbc:mysql://${DOCKER_HOST_IP:localhost}:9190/credit_db?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: mysqlpw
    maximum-pool-size: 100
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    swa.order-service: ERROR
    org.hibernate: ERROR