server:
  port: 9191

spring:
  cloud:
    stream:
      function:
        definition: creditOrderEventProcessor;verdictEventSubscriber
      bindings:
        creditOrderEventProcessor-in-0:
          destination: order-credit
        creditOrderEventProcessor-out-0:
          destination: verdicts
        verdictEventSubscriber-in-0:
          destination: verdicts
        verdictEventSubscriber-out-0:
          destination: credit-order
  datasource:
    url: jdbc:mysql://${DOCKER_HOST_IP:localhost}:9190/credit_db?createDatabaseIfNotExist=true
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: mysqlpw
    maximum-pool-size: 100
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
