server:
  port: 9191

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS}
      function:
        definition: creditOrderEventProcessor
      bindings:
        creditOrderEventProcessor-in-0:
          destination: order-credit
        creditOrderEventProcessor-out-0:
          destination: credit-order
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:9190/credit_db}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:mysqluser}
    password: ${DB_PASSWORD:mysqlpw}
    maximum-pool-size: 100
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    swa.order-service: ERROR
    org.hibernate: ERROR