version: "3"
services:
  customer-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: postgres://postgres:password@postgres-db:5432/customer-db
      KAFKA_BROKERS: ${DOCKER_HOST_IP}:9092;${DOCKER_HOST_IP}:9093;${DOCKER_HOST_IP}:9094
    depends_on:
      postgres-db:
        condition: service_healthy
    ports: 
      - 3000:3000
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
  postgres-db:
      image: postgres
      ports:
        - 5432:5432
      restart: always
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
      environment:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: customer-db

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      GUNICORN_ACCESS_LOGFILE: /dev/null
    ports:
      - "8098:80"
    