version: "3"
services:
  postgres-db:
      image: postgres
      ports:
        - 5432:5432
      restart: always
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
      environment:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: customer-db
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      GUNICORN_ACCESS_LOGFILE: /dev/null
    ports:
      - "5050:80"
  customer-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: postgres://postgres:password@postgres-db:5432/customer-db
      EVENTUATE_TRAM_MYSQL_HOST: mysql
      EVENTUATE_TRAM_MYSQL_PORT: 3306
      EVENTUATE_TRAM_MYSQL_DATABASE: eventuate
      EVENTUATE_TRAM_MYSQL_USERNAME: mysqluser
      EVENTUATE_TRAM_MYSQL_PASSWORD: mysqlpw
      EVENTUATE_TRAM_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      postgres-db:
        condition: service_healthy
    ports: 
      - 3000:3000
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    